# fly.toml - Versión final y corregida
app = 'rhino-requests-portal'
primary_region = 'mia'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = "sh -c 'python manage.py collectstatic --no-input && /entrypoint.sh python manage.py migrate --no-input'"

[env]
  PORT = '8000'

# Definimos explícitamente nuestros dos procesos
[processes]
  web = "/entrypoint.sh gunicorn requests_webpage.wsgi"
  worker = "/entrypoint.sh python manage.py qcluster"

# Definimos nuestro servicio web público, que ejecuta el proceso 'web'
[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["web"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"