# Generated by Django 5.2 on 2025-04-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_userrecordsrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
