# Generated by Django 5.2 on 2025-04-25 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_customuser_timezone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrecordsrequest',
            options={'ordering': ['-timestamp'], 'verbose_name': 'User Records Request', 'verbose_name_plural': 'User Records Requests'},
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userrecordsrequest',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
