# Generated by Django 5.2 on 2025-04-25 01:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_userrecordsrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecordsrequest',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
