# Generated by Django 5.2 on 2025-04-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_userrecordsrequest_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecordsrequest',
            name='type_of_process',
            field=models.CharField(choices=[('user_records', 'User Records')], default='user_records', max_length=50),
        ),
    ]
