# Generated by Django 5.2 on 2025-04-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_userrecordsrequest_type_of_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecordsrequest',
            name='user_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='user_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
