# Generated by Django 5.2 on 2025-04-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_userrecordsrequest_user_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecordsrequest',
            name='user_file',
        ),
        migrations.AlterField(
            model_name='userrecordsrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('blocked', 'Blocked'), ('pending_approval', 'Pending for Approval')], default='pending', max_length=20),
        ),
    ]
