# Generated by Django 5.2 on 2025-04-26 01:52

import tasks.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_userrecordsrequest_user_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecordsrequest',
            name='user_file',
            field=models.FileField(blank=True, null=True, upload_to='user_records/', validators=[tasks.validators.validate_file_size]),
        ),
    ]
