# Generated by Django 5.2 on 2025-04-26 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_userrecordsrequest_user_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecordsrequest',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='blocked_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='operated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='qa_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='qa_in_progress_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='qa_pending_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='qa_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='resolve_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userrecordsrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrecordsrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('blocked', 'Blocked'), ('pending_approval', 'Pending for Approval'), ('qa_pending', 'QA Pending'), ('qa_in_progress', 'QA In Progress')], default='pending', max_length=20),
        ),
    ]
