# Generated by Django 5.2 on 2025-04-26 21:27

import tasks.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_userrecordsrequest_blocked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecordsrequest',
            name='resolved_file',
            field=models.FileField(blank=True, null=True, upload_to='user_records/', validators=[tasks.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='resolved_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
