# Generated by Django 5.2 on 2025-04-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_userrecordsrequest_bulk_updates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecordsrequest',
            name='processing_reports_rows',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
