# Generated by Django 5.2 on 2025-04-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_userrecordsrequest_processing_reports_rows'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_update_price', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('property_update_price', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('bulk_update_price', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('manual_update_price', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('csv_update_price', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('processing_report_price', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('user_update_cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('property_update_cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('bulk_update_cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('manual_update_cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('csv_update_cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('processing_report_cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Operation Price and Cost',
                'verbose_name_plural': 'Operation Prices and Costs',
            },
        ),
    ]
