# Generated by Django 5.2 on 2025-04-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_operationprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operationprice',
            old_name='bulk_update_cost',
            new_name='bulk_update_operate_cost',
        ),
        migrations.RenameField(
            model_name='operationprice',
            old_name='csv_update_cost',
            new_name='bulk_update_qa_cost',
        ),
        migrations.RenameField(
            model_name='operationprice',
            old_name='manual_update_cost',
            new_name='csv_update_operate_cost',
        ),
        migrations.RenameField(
            model_name='operationprice',
            old_name='processing_report_cost',
            new_name='csv_update_qa_cost',
        ),
        migrations.RenameField(
            model_name='operationprice',
            old_name='property_update_cost',
            new_name='manual_update_operate_cost',
        ),
        migrations.RenameField(
            model_name='operationprice',
            old_name='user_update_cost',
            new_name='manual_update_qa_cost',
        ),
        migrations.AddField(
            model_name='operationprice',
            name='processing_report_operate_cost',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='operationprice',
            name='processing_report_qa_cost',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='operationprice',
            name='property_update_operate_cost',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='operationprice',
            name='property_update_qa_cost',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='operationprice',
            name='user_update_operate_cost',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='operationprice',
            name='user_update_qa_cost',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
