# Generated by Django 5.2 on 2025-04-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_rename_bulk_update_cost_operationprice_bulk_update_operate_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecordsrequest',
            name='deactivation_toggle_active_policies',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='deactivation_toggle_context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='deactivation_toggle_leadership_approval',
            field=models.CharField(blank=True, choices=[('carolyn_walentisch', 'Carolyn Walentisch'), ('cristine_brown', 'Cristine Brown'), ('shay_chang', 'Shay Chang'), ('chelsea_strickland', 'Chelsea Strickland')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='deactivation_toggle_marked_as_churned',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='deactivation_toggle_properties',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='deactivation_toggle_properties_with_policies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='deactivation_toggle_type',
            field=models.CharField(blank=True, choices=[('partner_deactivation', 'Partner Deactivation'), ('property_deactivation', 'Property Deactivation'), ('toggle_on_invites', 'Toggle on invites'), ('toggle_off_invites', 'Toggle off invites'), ('toggle_off_homepage_signups', 'Toggle off homepage sing-ups'), ('toggle_on_cash_deposits', 'Toggle on cash deposits'), ('toggle_off_cash_deposits', 'Toggle off cash deposits')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userrecordsrequest',
            name='type_of_process',
            field=models.CharField(choices=[('user_records', 'User Records'), ('deactivation_toggle', 'Deactivation and Toggle')], default='user_records', max_length=50),
        ),
    ]
