# Generated by Django 5.2 on 2025-04-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_userrecordsrequest_deactivation_toggle_active_policies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecordsrequest',
            name='user_groups_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
