# Generated by Django 5.2 on 2025-04-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_userrecordsrequest_unit_transfer_new_partner_prospect_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecordsrequest',
            name='unit_transfer_new_partner_prospect_name',
        ),
        migrations.RemoveField(
            model_name='userrecordsrequest',
            name='unit_transfer_new_policyholders',
        ),
        migrations.RemoveField(
            model_name='userrecordsrequest',
            name='unit_transfer_proof_of_sales',
        ),
        migrations.RemoveField(
            model_name='userrecordsrequest',
            name='unit_transfer_prospect_landlord_type',
        ),
        migrations.RemoveField(
            model_name='userrecordsrequest',
            name='unit_transfer_prospect_portfolio_size',
        ),
        migrations.RemoveField(
            model_name='userrecordsrequest',
            name='unit_transfer_receiving_partner_psm',
        ),
        migrations.RemoveField(
            model_name='userrecordsrequest',
            name='unit_transfer_type',
        ),
        migrations.AlterField(
            model_name='userrecordsrequest',
            name='type_of_process',
            field=models.CharField(choices=[('user_records', 'User Records'), ('deactivation_toggle', 'Deactivation and Toggle')], default='user_records', max_length=50),
        ),
    ]
