# Generated by Django 5.2 on 2025-04-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_remove_userrecordsrequest_unit_transfer_new_partner_prospect_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecordsrequest',
            name='unit_transfer_new_partner_prospect_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='unit_transfer_new_policyholders',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='unit_transfer_proof_of_sale',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='unit_transfer_properties',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='unit_transfer_prospect_landlord_type',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('3rd_party_manager', '3rd Party Manager'), ('owner_manager', 'Owner-Manager'), ('broker', 'Broker'), ('vendor', 'Vendor'), ('reit', 'REIT'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='unit_transfer_prospect_portfolio_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='unit_transfer_receiving_partner_psm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='unit_transfer_type',
            field=models.CharField(blank=True, choices=[('partner_to_prospect', 'Partner to Prospect'), ('partner_to_partner', 'Partner to Partner')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='unit_transfer_user_email_addresses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userrecordsrequest',
            name='type_of_process',
            field=models.CharField(choices=[('user_records', 'User Records'), ('deactivation_toggle', 'Deactivation and Toggle'), ('unit_transfer', 'Unit Transfer')], default='user_records', max_length=50),
        ),
    ]
