# Generated by Django 5.2 on 2025-04-28 14:52

import tasks.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_userrecordsrequest_unit_transfer_new_partner_prospect_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecordsrequest',
            name='xml_carrier_rvic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='xml_carrier_ssic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='xml_state',
            field=models.CharField(blank=True, choices=[('CA', 'CA'), ('CO', 'CO'), ('FL', 'FL'), ('GA', 'GA'), ('IL', 'IL'), ('MN', 'MN'), ('MS', 'MS'), ('NC', 'NC'), ('NJ', 'NJ'), ('OK', 'OK'), ('SC', 'SC'), ('TX', 'TX'), ('WA', 'WA')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='userrecordsrequest',
            name='partner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userrecordsrequest',
            name='type_of_process',
            field=models.CharField(choices=[('user_records', 'User Records'), ('deactivation_toggle', 'Deactivation and Toggle'), ('unit_transfer', 'Unit Transfer'), ('generating_xml', 'Generating XML files')], default='user_records', max_length=50),
        ),
        migrations.AlterField(
            model_name='userrecordsrequest',
            name='user_file',
            field=models.FileField(blank=True, null=True, upload_to='user_uploads/', validators=[tasks.validators.validate_file_size]),
        ),
    ]
