# Generated by Django 5.2 on 2025-04-28 15:15

import tasks.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_userrecordsrequest_xml_carrier_rvic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecordsrequest',
            name='xml_rvic_zip_file',
            field=models.FileField(blank=True, null=True, upload_to='xml_zip_files/', validators=[tasks.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='xml_ssic_zip_file',
            field=models.FileField(blank=True, null=True, upload_to='xml_zip_files/', validators=[tasks.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='userrecordsrequest',
            name='user_file',
            field=models.FileField(blank=True, null=True, upload_to='user_uploads/', validators=[tasks.validators.validate_file_size], verbose_name='Upload Spreadsheet'),
        ),
        migrations.AlterField(
            model_name='userrecordsrequest',
            name='xml_state',
            field=models.CharField(blank=True, choices=[('CA', 'CA'), ('CO', 'CO'), ('FL', 'FL'), ('GA', 'GA'), ('IL', 'IL'), ('MN', 'MN'), ('MS', 'MS'), ('NC', 'NC'), ('NJ', 'NJ'), ('OK', 'OK'), ('SC', 'SC'), ('TX', 'TX'), ('UT', 'UT'), ('WA', 'WA')], max_length=2, null=True),
        ),
    ]
