# Generated by Django 5.2 on 2025-04-28 19:34

import tasks.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_remove_userrecordsrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecordsrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('blocked', 'Blocked'), ('pending_approval', 'Pending for Approval'), ('qa_pending', 'QA Pending'), ('qa_in_progress', 'QA In Progress')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userrecordsrequest',
            name='user_file',
            field=models.FileField(blank=True, null=True, upload_to='user_uploads/', validators=[tasks.validators.validate_file_size], verbose_name='Upload File'),
        ),
    ]
