# Generated by Django 5.2 on 2025-04-28 19:39

import tasks.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_userrecordsrequest_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecordsrequest',
            name='address_validation_opportunity_id',
        ),
        migrations.RemoveField(
            model_name='userrecordsrequest',
            name='address_validation_policyholders',
        ),
        migrations.RemoveField(
            model_name='userrecordsrequest',
            name='address_validation_user_email_addresses',
        ),
        migrations.AlterField(
            model_name='userrecordsrequest',
            name='type_of_process',
            field=models.CharField(choices=[('user_records', 'User Records'), ('deactivation_toggle', 'Deactivation and Toggle'), ('unit_transfer', 'Unit Transfer'), ('generating_xml', 'Generating XML files')], default='user_records', max_length=50),
        ),
        migrations.AlterField(
            model_name='userrecordsrequest',
            name='user_file',
            field=models.FileField(blank=True, null=True, upload_to='user_uploads/', validators=[tasks.validators.validate_file_size], verbose_name='Upload Spreadsheet'),
        ),
    ]
