# Generated by Django 5.2 on 2025-04-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0031_userrecordsrequest_address_validation_opportunity_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecordsrequest',
            name='address_validation_opportunity_id',
        ),
        migrations.RemoveField(
            model_name='userrecordsrequest',
            name='address_validation_policyholders',
        ),
        migrations.RemoveField(
            model_name='userrecordsrequest',
            name='address_validation_user_email_addresses',
        ),
        migrations.AlterField(
            model_name='userrecordsrequest',
            name='type_of_process',
            field=models.CharField(choices=[('user_records', 'User Records'), ('deactivation_toggle', 'Deactivation and Toggle'), ('unit_transfer', 'Unit Transfer'), ('generating_xml', 'Generating XML files')], default='user_records', max_length=50),
        ),
    ]
