# Generated by Django 5.2 on 2025-04-29 03:06

import tasks.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0032_remove_userrecordsrequest_address_validation_opportunity_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockedmessage',
            options={'ordering': ['-blocked_at']},
        ),
        migrations.AlterModelOptions(
            name='rejectedmessage',
            options={'ordering': ['-rejected_at']},
        ),
        migrations.AlterModelOptions(
            name='resolvedmessage',
            options={'ordering': ['-resolved_at']},
        ),
        migrations.AlterModelOptions(
            name='userrecordsrequest',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Request', 'verbose_name_plural': 'Requests'},
        ),
        migrations.AlterField(
            model_name='userrecordsrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='userrecordsrequest',
            name='deactivation_toggle_type',
            field=models.CharField(blank=True, choices=[('partner_deactivation', 'Partner Deactivation'), ('property_deactivation', 'Property Deactivation'), ('toggle_on_invites', 'Toggle on invites'), ('toggle_off_invites', 'Toggle off invites'), ('toggle_off_homepage_signups', 'Toggle off homepage sign-ups'), ('toggle_on_cash_deposits', 'Toggle on cash deposits'), ('toggle_off_cash_deposits', 'Toggle off cash deposits')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userrecordsrequest',
            name='operated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='userrecordsrequest',
            name='partner_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userrecordsrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('blocked', 'Blocked'), ('pending_approval', 'Pending for Approval'), ('qa_pending', 'QA Pending'), ('qa_in_progress', 'QA In Progress')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userrecordsrequest',
            name='type_of_process',
            field=models.CharField(choices=[('user_records', 'User Records'), ('deactivation_toggle', 'Deactivation and Toggle'), ('unit_transfer', 'Unit Transfer'), ('generating_xml', 'Generating XML files')], db_index=True, default='user_records', max_length=50),
        ),
        migrations.AlterField(
            model_name='userrecordsrequest',
            name='user_file',
            field=models.FileField(blank=True, null=True, upload_to='user_uploads/', validators=[tasks.validators.validate_file_size], verbose_name='Upload File'),
        ),
    ]
