# Generated by Django 5.2 on 2025-04-30 01:33

import django.db.models.deletion
import tasks.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0034_userrecordsrequest_address_validation_opportunity_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressValidationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='address_validation_uploads/', validators=[tasks.validators.validate_file_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(limit_choices_to={'type_of_process': 'address_validation'}, on_delete=django.db.models.deletion.CASCADE, related_name='address_validation_files', to='tasks.userrecordsrequest')),
            ],
            options={
                'verbose_name': 'Address Validation File',
                'verbose_name_plural': 'Address Validation Files',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
