# Generated by Django 5.2 on 2025-04-30 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0035_addressvalidationfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressvalidationfile',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_validation_files', to='tasks.userrecordsrequest'),
        ),
        migrations.AlterField(
            model_name='addressvalidationfile',
            name='uploaded_file',
            field=models.FileField(upload_to='address_validation_uploads/'),
        ),
    ]
