# Generated by Django 5.2 on 2025-04-30 13:19

import tasks.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0036_alter_addressvalidationfile_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressvalidationfile',
            name='uploaded_file',
            field=models.FileField(upload_to='address_validation_uploads/', validators=[tasks.validators.validate_file_size]),
        ),
    ]
