# Generated by Django 5.2 on 2025-04-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0037_alter_addressvalidationfile_uploaded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecordsrequest',
            name='stripe_premium_disputes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rhino Super Premium Disputes'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='stripe_ri_disputes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rhino Super RI Disputes'),
        ),
        migrations.AlterField(
            model_name='userrecordsrequest',
            name='type_of_process',
            field=models.CharField(choices=[('user_records', 'User Records'), ('deactivation_toggle', 'Deactivation and Toggle'), ('unit_transfer', 'Unit Transfer'), ('generating_xml', 'Generating XML files'), ('address_validation', 'Address Validation'), ('stripe_disputes', 'Stripe Disputes')], db_index=True, default='user_records', max_length=50),
        ),
    ]
