# Generated by Django 5.2 on 2025-05-01 14:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0038_userrecordsrequest_stripe_premium_disputes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecordsrequest',
            name='property_records_bank_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='property_records_corrected_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='property_records_coverage_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(Decimal('330.00')), django.core.validators.MaxValueValidator(Decimal('200000000.00'))]),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='property_records_coverage_multiplier',
            field=models.CharField(blank=True, choices=[('0.5', '0.5x'), ('1.0', '1x'), ('1.5', '1.5x'), ('2.0', '2x'), ('2.5', '2.5x'), ('3.0', '3x'), ('4.0', '4x'), ('5.0', '5x'), ('6.0', '6x')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='property_records_coverage_type',
            field=models.CharField(blank=True, choices=[('multiplier', 'Multiplier'), ('amount', 'Amount')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='property_records_integration_codes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='property_records_integration_type',
            field=models.CharField(blank=True, choices=[('yardi', 'Yardi'), ('realpage', 'RealPage'), ('udr', 'UDR'), ('rent_manager', 'Rent Manager'), ('mri', 'MRI'), ('entrata', 'Entrata'), ('eqr', 'EQR')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='property_records_new_names',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='property_records_new_pmc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='property_records_new_policyholder',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='property_records_properties',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='property_records_type',
            field=models.CharField(blank=True, choices=[('property_name', 'Property Name'), ('property_management_company', 'Property Management Company'), ('property_legal_entity', 'Property Legal Entity'), ('address', 'Address'), ('property_type', 'Property Type'), ('property_units', 'Property Units'), ('coverage_type_amount', 'Coverage Type/Amount'), ('integration_code', 'Integration Code'), ('banking_information', 'Banking Information')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='property_records_units',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='property_records_updated_type',
            field=models.CharField(blank=True, choices=[('single_family', 'Single-Family'), ('garden_community', 'Garden-Community'), ('multifamily', 'Multifamily')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userrecordsrequest',
            name='type_of_process',
            field=models.CharField(choices=[('user_records', 'User Records'), ('deactivation_toggle', 'Deactivation and Toggle'), ('unit_transfer', 'Unit Transfer'), ('generating_xml', 'Generating XML files'), ('address_validation', 'Address Validation'), ('stripe_disputes', 'Stripe Disputes'), ('property_records', 'Property Records')], db_index=True, default='user_records', max_length=50),
        ),
    ]
