# Generated by Django 5.2 on 2025-05-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0039_userrecordsrequest_property_records_bank_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecordsrequest',
            name='properties',
            field=models.TextField(blank=True, null=True, verbose_name='Properties Affected'),
        ),
    ]
