# Generated by Django 5.2 on 2025-05-01 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0040_userrecordsrequest_properties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecordsrequest',
            name='deactivation_toggle_properties',
        ),
        migrations.RemoveField(
            model_name='userrecordsrequest',
            name='property_records_properties',
        ),
        migrations.RemoveField(
            model_name='userrecordsrequest',
            name='unit_transfer_properties',
        ),
    ]
