# Generated by Django 5.2 on 2025-05-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0041_remove_userrecordsrequest_deactivation_toggle_properties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecordsrequest',
            name='team',
            field=models.CharField(blank=True, choices=[('team_revenue', 'Revenue'), ('team_support', 'Support'), ('team_compliance', 'Compliance'), ('team_accounting', 'Accounting')], db_index=True, max_length=20, null=True, verbose_name='Assigned Team'),
        ),
    ]
