# Generated by Django 5.2 on 2025-05-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0042_userrecordsrequest_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecordsrequest',
            name='team',
            field=models.CharField(blank=True, choices=[('Revenue', 'Revenue'), ('Support', 'Support'), ('Compliance', 'Compliance'), ('Accounting', 'Accounting')], db_index=True, max_length=20, null=True, verbose_name='Assigned Team'),
        ),
    ]
