# Generated by Django 5.2 on 2025-05-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0043_alter_userrecordsrequest_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecordsrequest',
            name='manual_updated_units',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Manual Updated Units'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='operator_spreadsheet_link',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Operator Spreadsheet Link'),
        ),
    ]
