# Generated by Django 5.2 on 2025-05-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0046_userrecordsrequest_update_needed_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecordsrequest',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='Date for which the request is scheduled to become active (pending).', null=True, verbose_name='Scheduled Date'),
        ),
        migrations.AlterField(
            model_name='userrecordsrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('blocked', 'Blocked'), ('pending_approval', 'Pending for Approval'), ('qa_pending', 'QA Pending'), ('qa_in_progress', 'QA In Progress')], db_index=True, default='pending', max_length=20),
        ),
    ]
