# Generated by Django 5.2.1 on 2025-05-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0047_userrecordsrequest_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecordsrequest',
            name='effective_start_time_for_tat',
            field=models.DateTimeField(blank=True, help_text='Timestamp marking the real start of the work cycle for TAT calculation.', null=True, verbose_name='Effective Start Time for TAT'),
        ),
    ]
