# Generated by Django 5.2.1 on 2025-05-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0048_userrecordsrequest_effective_start_time_for_tat'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecordsrequest',
            name='is_rejected_previously',
            field=models.BooleanField(default=False, help_text='Indicates if the request was rejected by QA and needs re-submission to QA.', verbose_name='Previously Rejected by QA'),
        ),
    ]
