# Generated by Django 5.2.1 on 2025-05-20 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0049_userrecordsrequest_is_rejected_previously'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecordsrequest',
            name='salesforce_account_manager',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Salesforce Account Manager'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='salesforce_closed_won_date',
            field=models.DateField(blank=True, null=True, verbose_name='Salesforce Closed Won Date'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='salesforce_information_needed_for_assets',
            field=models.TextField(blank=True, null=True, verbose_name='Salesforce Information Needed For Assets'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='salesforce_leasing_integration_software',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Salesforce Leasing Integration Software'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='salesforce_link',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Salesforce Opportunity Link'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='salesforce_number_of_units',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Salesforce Number of Units'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='salesforce_opportunity_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Salesforce Opportunity Name'),
        ),
        migrations.CreateModel(
            name='SalesforceAttachmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='File Name')),
                ('file_extension', models.CharField(blank=True, max_length=50, null=True, verbose_name='File Extension')),
                ('salesforce_file_link', models.URLField(max_length=1024, verbose_name='Salesforce File Link')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesforce_attachments', to='tasks.userrecordsrequest', verbose_name='Associated Request')),
            ],
            options={
                'verbose_name': 'Salesforce Attachment Log',
                'verbose_name_plural': 'Salesforce Attachment Logs',
                'ordering': ['-request__timestamp', 'file_name'],
            },
        ),
    ]
