# Generated by Django 5.2.1 on 2025-05-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0050_userrecordsrequest_salesforce_account_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecordsrequest',
            name='salesforce_standard_opp_id',
            field=models.CharField(blank=True, help_text='The standard 18-character ID of the Opportunity in Salesforce.', max_length=18, null=True, verbose_name='Salesforce Standard Opportunity ID'),
        ),
    ]
