# Generated by Django 5.2.1 on 2025-05-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0051_userrecordsrequest_salesforce_standard_opp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecordsrequest',
            name='assets_uploaded',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Assets Uploaded (AV)'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='av_number_of_units',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Units (AV Operation)'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='failed_output_link',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Failed Output Link (AV)'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='link_to_assets',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Link to Assets (AV)'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='rhino_accounts_created',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Rhino Accounts Created? (AV)'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='success_output_link',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Success Output Link (AV)'),
        ),
    ]
