# Generated by Django 5.2.1 on 2025-05-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0052_userrecordsrequest_assets_uploaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecordsrequest',
            name='av_number_of_invalid_units',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Number of Invalid Units (AV Operation)'),
        ),
    ]
