# Generated by Django 5.2.1 on 2025-05-22 16:14

import tasks.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0053_userrecordsrequest_av_number_of_invalid_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecordsrequest',
            name='operator_rvic_file_slot1',
            field=models.FileField(blank=True, help_text='Slot 1 for RVIC file uploaded by operator.', null=True, upload_to='operator_xml_files/', validators=[tasks.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='operator_rvic_file_slot2',
            field=models.FileField(blank=True, help_text='Slot 2 for RVIC file (e.g., ZIP for UT_RVIC) by operator.', null=True, upload_to='operator_xml_files/', validators=[tasks.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='operator_ssic_file_slot1',
            field=models.FileField(blank=True, help_text='Slot 1 for SSIC file uploaded by operator.', null=True, upload_to='operator_xml_files/', validators=[tasks.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='operator_ssic_file_slot2',
            field=models.FileField(blank=True, help_text='Slot 2 for SSIC file (e.g., ZIP for UT_SSIC) by operator.', null=True, upload_to='operator_xml_files/', validators=[tasks.validators.validate_file_size]),
        ),
    ]
