# Generated by Django 5.2.1 on 2025-05-25 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0055_userrecordsrequest_cancelled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecordsrequest',
            name='update_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Update Requested At'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='update_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_records_update_requested_by', to=settings.AUTH_USER_MODEL, verbose_name='Update Requested By'),
        ),
    ]
