# Generated by Django 5.2.1 on 2025-05-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0056_userrecordsrequest_update_requested_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTaskToggle',
            fields=[
                ('task_name', models.CharField(help_text='Unique identifier for the scheduled task.', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='MCheck to enable task execution. Uncheck to pause.')),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scheduled Task Toggle',
                'verbose_name_plural': 'Scheduled Task Toggles',
            },
        ),
    ]
