# Generated by Django 5.2.1 on 2025-05-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0057_scheduledtasktoggle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationprice',
            name='manual_update_operate_cost',
        ),
        migrations.RemoveField(
            model_name='operationprice',
            name='manual_update_price',
        ),
        migrations.RemoveField(
            model_name='operationprice',
            name='manual_update_qa_cost',
        ),
        migrations.AddField(
            model_name='operationprice',
            name='address_validation_unit_operate_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Address Validation Unit Operate Cost'),
        ),
        migrations.AddField(
            model_name='operationprice',
            name='address_validation_unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Address Validation Unit Price'),
        ),
        migrations.AddField(
            model_name='operationprice',
            name='address_validation_unit_qa_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Address Validation Unit QA Cost'),
        ),
        migrations.AddField(
            model_name='operationprice',
            name='manual_property_update_operate_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Manual Property Update Operate Cost'),
        ),
        migrations.AddField(
            model_name='operationprice',
            name='manual_property_update_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Manual Property Update Price'),
        ),
        migrations.AddField(
            model_name='operationprice',
            name='manual_property_update_qa_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Manual Property Update QA Cost'),
        ),
        migrations.AddField(
            model_name='operationprice',
            name='manual_unit_update_operate_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Manual Unit Update Operate Cost'),
        ),
        migrations.AddField(
            model_name='operationprice',
            name='manual_unit_update_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Manual Unit Update Price'),
        ),
        migrations.AddField(
            model_name='operationprice',
            name='manual_unit_update_qa_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Manual Unit Update QA Cost'),
        ),
        migrations.AddField(
            model_name='operationprice',
            name='stripe_dispute_operate_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Stripe Dispute Operate Cost'),
        ),
        migrations.AddField(
            model_name='operationprice',
            name='stripe_dispute_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Stripe Dispute Price'),
        ),
        migrations.AddField(
            model_name='operationprice',
            name='stripe_dispute_qa_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Stripe Dispute QA Cost'),
        ),
        migrations.AddField(
            model_name='operationprice',
            name='xml_file_operate_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='XML File Operate Cost'),
        ),
        migrations.AddField(
            model_name='operationprice',
            name='xml_file_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='XML File Price'),
        ),
        migrations.AddField(
            model_name='operationprice',
            name='xml_file_qa_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='XML File QA Cost'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='bulk_update_operate_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Bulk Update Operate Cost'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='bulk_update_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Bulk Update Price'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='bulk_update_qa_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Bulk Update QA Cost'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='csv_update_operate_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='CSV Update Row Operate Cost'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='csv_update_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='CSV Update Row Price'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='csv_update_qa_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='CSV Update Row QA Cost'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='processing_report_operate_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Processing Report Row Operate Cost'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='processing_report_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Processing Report Row Price'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='processing_report_qa_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Processing Report Row QA Cost'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='property_update_operate_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='User Update Operate Cost'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='property_update_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Property Update Price'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='property_update_qa_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Property Update QA Cost'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='user_update_operate_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='User Update Operate Cost'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='user_update_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='User Update Price'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='user_update_qa_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='User Update QA Cost'),
        ),
    ]
