# Generated by Django 5.2.1 on 2025-05-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0058_remove_operationprice_manual_update_operate_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecordsrequest',
            name='grand_total_client_price_completed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Grand Total Price'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='grand_total_operate_cost_completed',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=8, null=True, verbose_name='Grand Total (Operate Cost) at Completion'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='grand_total_qa_cost_completed',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=8, null=True, verbose_name='Grand Total (QA Cost) at Completion'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='subtotal_address_validation_unit_client_price_completed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Address Validation Unit Price Subtotal'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='subtotal_address_validation_unit_operate_cost_completed',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=8, null=True, verbose_name='Address Validation Unit Subtotal (Operate Cost)'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='subtotal_address_validation_unit_qa_cost_completed',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=8, null=True, verbose_name='Address Validation Unit Subtotal (QA Cost)'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='subtotal_bulk_update_client_price_completed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Bulk Update Price Subtotal'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='subtotal_bulk_update_operate_cost_completed',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=8, null=True, verbose_name='Bulk Update Subtotal (Operate Cost)'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='subtotal_bulk_update_qa_cost_completed',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=8, null=True, verbose_name='Bulk Update Subtotal (QA Cost)'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='subtotal_csv_update_client_price_completed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='CSV Update Price Subtotal'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='subtotal_csv_update_operate_cost_completed',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=8, null=True, verbose_name='CSV Update Subtotal (Operate Cost)'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='subtotal_csv_update_qa_cost_completed',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=8, null=True, verbose_name='CSV Update Subtotal (QA Cost)'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='subtotal_manual_property_update_client_price_completed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Manual Property Update Price Subtotal'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='subtotal_manual_property_update_operate_cost_completed',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=8, null=True, verbose_name='Manual Property Update Subtotal (Operate Cost)'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='subtotal_manual_property_update_qa_cost_completed',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=8, null=True, verbose_name='Manual Property Update Subtotal (QA Cost)'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='subtotal_manual_unit_update_client_price_completed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Manual Unit Update Price Subtotal'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='subtotal_manual_unit_update_operate_cost_completed',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=8, null=True, verbose_name='Manual Unit Update Subtotal (Operate Cost)'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='subtotal_manual_unit_update_qa_cost_completed',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=8, null=True, verbose_name='Manual Unit Update Subtotal (QA Cost)'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='subtotal_processing_report_client_price_completed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Processing Report Price Subtotal'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='subtotal_processing_report_operate_cost_completed',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=8, null=True, verbose_name='Processing Report Subtotal (Operate Cost)'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='subtotal_processing_report_qa_cost_completed',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=8, null=True, verbose_name='Processing Report Subtotal (QA Cost)'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='subtotal_property_update_client_price_completed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Property Update Price Subtotal'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='subtotal_property_update_operate_cost_completed',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=8, null=True, verbose_name='Property Update Subtotal (Operate Cost)'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='subtotal_property_update_qa_cost_completed',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=8, null=True, verbose_name='Property Update Subtotal (QA Cost)'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='subtotal_stripe_dispute_client_price_completed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Stripe Dispute Price Subtotal'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='subtotal_stripe_dispute_operate_cost_completed',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=8, null=True, verbose_name='Stripe Dispute Subtotal (Operate Cost)'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='subtotal_stripe_dispute_qa_cost_completed',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=8, null=True, verbose_name='Stripe Dispute Subtotal (QA Cost)'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='subtotal_user_update_client_price_completed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='User Update Price Subtotal'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='subtotal_user_update_operate_cost_completed',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=8, null=True, verbose_name='User Update Subtotal (Operate Cost)'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='subtotal_user_update_qa_cost_completed',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=8, null=True, verbose_name='User Update Subtotal (QA Cost)'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='subtotal_xml_file_client_price_completed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='XML File Price Subtotal'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='subtotal_xml_file_operate_cost_completed',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=8, null=True, verbose_name='XML File Subtotal (Operate Cost)'),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='subtotal_xml_file_qa_cost_completed',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=8, null=True, verbose_name='XML File Subtotal (QA Cost)'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='address_validation_unit_operate_cost',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='Address Validation Unit Operate Cost'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='address_validation_unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Address Validation Unit Price'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='address_validation_unit_qa_cost',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='Address Validation Unit QA Cost'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='bulk_update_operate_cost',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='Bulk Update Operate Cost'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='bulk_update_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Bulk Update Price'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='bulk_update_qa_cost',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='Bulk Update QA Cost'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='csv_update_operate_cost',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='CSV Update Row Operate Cost'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='csv_update_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='CSV Update Row Price'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='csv_update_qa_cost',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='CSV Update Row QA Cost'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='manual_property_update_operate_cost',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='Manual Property Update Operate Cost'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='manual_property_update_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Manual Property Update Price'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='manual_property_update_qa_cost',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='Manual Property Update QA Cost'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='manual_unit_update_operate_cost',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='Manual Unit Update Operate Cost'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='manual_unit_update_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Manual Unit Update Price'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='manual_unit_update_qa_cost',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='Manual Unit Update QA Cost'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='processing_report_operate_cost',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='Processing Report Row Operate Cost'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='processing_report_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Processing Report Row Price'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='processing_report_qa_cost',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='Processing Report Row QA Cost'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='property_update_operate_cost',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='User Update Operate Cost'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='property_update_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Property Update Price'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='property_update_qa_cost',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='Property Update QA Cost'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='stripe_dispute_operate_cost',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='Stripe Dispute Operate Cost'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='stripe_dispute_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Stripe Dispute Price'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='stripe_dispute_qa_cost',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='Stripe Dispute QA Cost'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='user_update_operate_cost',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='User Update Operate Cost'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='user_update_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='User Update Price'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='user_update_qa_cost',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='User Update QA Cost'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='xml_file_operate_cost',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='XML File Operate Cost'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='xml_file_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='XML File Price'),
        ),
        migrations.AlterField(
            model_name='operationprice',
            name='xml_file_qa_cost',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='XML File QA Cost'),
        ),
    ]
