# Generated by Django 5.2.1 on 2025-06-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0059_userrecordsrequest_grand_total_client_price_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecordsrequest',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('pending_approval', 'Pending for Approval'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('qa_pending', 'QA Pending'), ('qa_in_progress', 'QA In Progress'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userrecordsrequest',
            name='type_of_process',
            field=models.CharField(choices=[('address_validation', 'Address Validation'), ('user_records', 'User Records'), ('property_records', 'Property Records'), ('unit_transfer', 'Unit Transfer'), ('deactivation_toggle', 'Deactivation and Toggle'), ('generating_xml', 'Generating XML files'), ('stripe_disputes', 'Stripe Disputes')], db_index=True, default='user_records', max_length=50),
        ),
    ]
