# Generated by Django 5.2.1 on 2025-06-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0060_alter_userrecordsrequest_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationToggle',
            fields=[
                ('event_key', models.CharField(help_text="Clave única para el evento de notificación (ej. 'new_request_created').", max_length=100, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(blank=True, help_text='Breve descripción de para qué es este evento de notificación.', max_length=255)),
                ('is_email_enabled', models.BooleanField(default=True, help_text='Marcar para habilitar las notificaciones por correo para este evento. Desmarcar para deshabilitar.')),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Control de Evento de Notificación',
                'verbose_name_plural': 'Controles de Eventos de Notificación',
                'ordering': ['description', 'event_key'],
            },
        ),
    ]
