# Generated by Django 5.2.1 on 2025-06-05 23:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0061_notificationtoggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecordsrequest',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Enter a percentage value (e.g., 15 for 15%) to be discounted from the grand total.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('100.0'))], verbose_name='Discount Percentage'),
        ),
    ]
