# Generated by Django 5.2.1 on 2025-06-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0062_userrecordsrequest_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecordsrequest',
            name='final_price_client_completed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='The final client price after any discounts have been applied. This field is calculated automatically.', max_digits=8, null=True, verbose_name='Final Price (with discount)'),
        ),
    ]
