# Generated by Django 5.2.1 on 2025-06-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0065_populate_toggles'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slack_member_id',
            field=models.CharField(blank=True, help_text='El ID de miembro de Slack del usuario (ej. U123ABCDE) para notificaciones.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='slack_thread_ts',
            field=models.CharField(blank=True, help_text='El timestamp del mensaje principal de Slack para agrupar notificaciones en un hilo.', max_length=50, null=True, verbose_name='Slack Thread Timestamp'),
        ),
    ]
