# Generated by Django 5.2.1 on 2025-06-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0066_customuser_slack_member_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationtoggle',
            options={'ordering': ['description', 'event_key'], 'verbose_name': 'Notification Toggle', 'verbose_name_plural': 'Notifications Toggle'},
        ),
        migrations.AddField(
            model_name='userrecordsrequest',
            name='email_thread_id',
            field=models.CharField(blank=True, help_text='The Message-ID of the first email, used to group notifications into a conversation thread.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='slack_member_id',
            field=models.CharField(blank=True, help_text='Slack User Id for notifications (optional)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userrecordsrequest',
            name='slack_thread_ts',
            field=models.CharField(blank=True, help_text='The timestamp (ts) of the parent Slack message, used to group notifications into a thread', max_length=50, null=True, verbose_name='Slack Thread Timestamp'),
        ),
    ]
