# Generated by Django 5.2.1 on 2025-06-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0067_alter_notificationtoggle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecordsrequest',
            name='email_thread_id',
            field=models.TextField(blank=True, help_text='Stores the chain of Message-IDs for email threading.', null=True),
        ),
    ]
