# Generated by Django 5.2.1 on 2025-07-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0068_alter_userrecordsrequest_email_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecordsrequest',
            name='deactivate_user',
            field=models.BooleanField(default=False, help_text='Set to true if the user(s) in the request should be deactivated from the portal.'),
        ),
    ]
